import{D as l}from"./assets/types.js";let u={...l};const c="data-fv-attached";chrome.storage.sync.get(l,e=>{u=e;const n=()=>{window.PipExt&&(window.PipExt.setupMessageListener(a),window.PipExt.setupAutoPip(a),window.PipExt.active=!!document.pictureInPictureElement,window.PipExt.updateButton())};n(),setTimeout(n,100),s()});chrome.storage.onChanged.addListener(e=>{var n;for(const t in e)u[t]=(n=e[t])==null?void 0:n.newValue;document.querySelectorAll(`video[${c}]`).forEach(t=>{t.removeAttribute(c)}),document.querySelectorAll(".fv-btn").forEach(t=>t.remove()),s()});const p={"top-right":"top:10px; right:10px;","top-left":"top:10px; left:10px;","bottom-right":"bottom:10px; right:10px;","bottom-left":"bottom:10px; left:10px;"};function m(e){const n=window.PipExt.createButton("fv-btn");n.title="Float this video (FloatVid)";const t=p[u.overlayPosition];return n.style.cssText=`
    position:absolute; ${t}
    z-index:2147483647;
    width:36px; height:36px; padding:6px;
    background:rgba(0,0,0,0.72);
    color:#fff; border:none; border-radius:7px;
    cursor:pointer; display:flex;
    align-items:center; justify-content:center;
    opacity:0; transition:opacity .18s ease, transform .12s ease;
    pointer-events:auto;
    backdrop-filter:blur(4px);
    box-shadow:0 2px 8px rgba(0,0,0,.4);
  `,n.addEventListener("mouseenter",()=>n.style.transform="scale(1.1)"),n.addEventListener("mouseleave",()=>n.style.transform="scale(1)"),n.addEventListener("click",o=>{o.stopImmediatePropagation(),o.preventDefault(),window.PipExt.toggle(e)}),n}function f(e){if(!u.showOverlayButton||e.hasAttribute(c))return;const n=e.getBoundingClientRect();if(n.width<100||n.height<60)return;e.setAttribute(c,"true"),window.PipExt.attachListeners(e);const t=e.parentElement;if(!t)return;getComputedStyle(t).position==="static"&&(t.style.position="relative");const o=m(e);t.appendChild(o);const i=()=>{o.style.opacity="1"},r=()=>{o.style.opacity="0"};t.addEventListener("mouseenter",i),t.addEventListener("mouseleave",r),new MutationObserver((g,d)=>{document.contains(e)||(o.remove(),t.removeEventListener("mouseenter",i),t.removeEventListener("mouseleave",r),d.disconnect())}).observe(document.documentElement,{childList:!0,subtree:!0})}function a(){const e=Array.from(document.querySelectorAll("video"));if(!e.length)return null;const n=e.filter(i=>{const r=i.getBoundingClientRect();return r.width>0&&r.height>0}),t=n.filter(i=>!i.paused&&!i.ended&&i.readyState>=2);return(t.length?t:n.length?n:e).sort((i,r)=>r.getBoundingClientRect().width*r.getBoundingClientRect().height-i.getBoundingClientRect().width*i.getBoundingClientRect().height)[0]??null}function s(){document.querySelectorAll("video").forEach(f)}new MutationObserver(s).observe(document.documentElement,{childList:!0,subtree:!0});document.readyState==="loading"?document.addEventListener("DOMContentLoaded",s):s();chrome.runtime.onMessage.addListener((e,n,t)=>{if(e.action==="toggle-pip"){const o=a();return o?(window.PipExt.toggle(o),t({success:!0,active:!!document.pictureInPictureElement})):t({success:!1,error:"No video found"}),!0}if(e.action==="exit-pip")return(document.pictureInPictureElement?document.exitPictureInPicture():Promise.resolve()).then(()=>t({success:!0,active:!1})),!0;if(e.action==="get-status")return t({success:!0,active:!!document.pictureInPictureElement}),!1});
